### ISSUE TITLE
Ga Bisa Pinjam Kembali Buku, Pesan Errornya Notice: Trying to get property 'num_rows' of non-object in /storage/ssd3/300/14913300/public_html/lib/utility.inc.php on line 627

### ISSUE THREAD

**Issue by gungsanjay** [slims/slims9_bulian#37] opened 2020-09-20 15:38 UTC

**Comment by heroesoebekti** [comment] 2020-09-20 15:44
Duplicate of #36

**Closed by heroesoebekti** 2020-09-20 15:44 UTC
